DROP TABLE IF EXISTS ai_invocations;
DROP TABLE IF EXISTS ai_drafts;
DROP TABLE IF EXISTS requirements;
DROP TABLE IF EXISTS project_members;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS users;
